### ISSUE TITLE
Double check everything related to inputs in database for final delivery 

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#13]
We are guessing some of the inputs. To prepare for the final delivery, we need to double check every input to make sure everything is right. 

```[tasklist]
### Tasks
- [ ] Check the format, length, type and etc. of every input
- [ ] Clear the dummy data entry in the database
- [ ] Set control on the format, length, type etc of input in database
```
