### ISSUE TITLE
Connect NOT FOUND input to database

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#4]
```[tasklist]
### Tasks
- [x] Try to connect one new input first
- [x] Connect the rest inputs to the database
- [x] Dig into the functions to clear with the input schematype
```
### schematype
- every input have a schematype, need to figure how the inputs were categorized 
- Not sure if it's important, but we'd better need to get everything right to prevent future problem
<img width="794" alt="Screen Shot 2023-05-04 at 14 03 49" src="https://user-images.githubusercontent.com/103902059/236290387-24dedf18-f898-4d99-946e-91e68604076f.png">

**Comment by ttaliacc** [comment]
Successfully connect 'barcode' input to database and read the value from DB. Can move forward to work on the rest NOT FOUND inputs.
<img width="636" alt="Screen Shot 2023-05-05 at 18 22 41" src="https://user-images.githubusercontent.com/103902059/236594119-9a252bea-ce4f-4ef1-b1ae-9811b0932f7c.png">

**Comment by ttaliacc** [comment]
Ask Adam to help update the label names in the database to match the input names in the occurrenceeditor.php file. @Tian-Tan

**Comment by ttaliacc** [comment]
Finish connecting the rest NOT FOUNDs with the database. But there are some functions and arrays related to the inputs, which may have effects on others parts of the website, so I'm trying to figure out what they are for.

**Comment by ttaliacc** [comment]
5ecdb5d Update all related functions/arrays I could found at this point with commit
