### ISSUE TITLE
Database update for dropdown/lookup function of inputs

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#7]
Some inputs need dropdown functionality. The database needs to be updated.

```[tasklist]
### Tasks
- [x] Investigate the links between tables related to "omocurrences"
- [x] Design a new table to store the data for one text field/ or find out the table to put the data if it exists
- [x] Implement the schema for one such table
- [x] Fill the table with dummy data
- [x] Investigate potential bugs related to implementation
- [x] Implement schema and fill dummy data for all other required fields
```

### Related issue
- #6 

### General idea
- Each input with dropdown function needs a unique table to store the value, and the dropdown list will go through this table to filter based on the inputs
- Need to clear with where is the input value from: historical value, third party, etc. 
- Double check the design of the database before getting started. 

### Inputs need dropdown/lookup functionality 
<img width="709" alt="Screen Shot 2023-05-04 at 14 38 09" src="https://user-images.githubusercontent.com/103902059/236297968-396a10aa-6c77-41bf-8bed-84debe10b00a.png">

### Example
<img width="996" alt="Screen Shot 2023-05-04 at 14 39 11" src="https://user-images.githubusercontent.com/103902059/236298179-fd652bea-f3f6-4de9-bf25-003d57cadea6.png">

### Fields with dropdown columns
1. Herbarium
2. Filed under
3. Current name
4. ID qualifier
5. Identified by
6. Collectors
7. Container
8. Collecting trip
9. Geography within
10. Higher Geography
11. Prep method
12. Format

**Comment by Tian-Tan** [comment]
The filedUnder column is updated to point to a table containing the values for the dropdown list: filedUnder_values. This still needs testing to discover potential bugs.

**Comment by Tian-Tan** [comment]
Added all tables for the dropdown columns, each holding the values possible for one of the dropdown lists, **except for** the "herbarium" and "id qualifier" fields, as they have less values so they can possibly be simply hard coded in the frontend.

**Comment by ttaliacc** [comment]
Error occurred when saving any edit of the form. The suspicion is that 764b25be8bcccd0da8c52a7e81f8438299863023 is the cause.

<img width="1183" alt="Screen Shot 2023-06-06 at 19 12 55" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/69ddf8df-aa3e-4cc8-810e-1a9e1cf1c15e">

**Comment by Tian-Tan** [comment]
> Error occurred when saving any edit of the form. The suspicion is that [764b25b](https://github.com/BU-Spark/se-Symbiota-portal/commit/764b25be8bcccd0da8c52a7e81f8438299863023) is the cause.
> 
> <img alt="Screen Shot 2023-06-06 at 19 12 55" width="1183" src="https://user-images.githubusercontent.com/103902059/243675717-69ddf8df-aa3e-4cc8-810e-1a9e1cf1c15e.png">

Bug fixed.

**Comment by Tian-Tan** [comment]
Dropdown tables have been standardized to have the same naming conventions and columns as some other tables in d9137b3fffba8119268f976c4de005bdcc92a20c

**Comment by ttaliacc** [comment]
@Tian-Tan  I think you've done everything with this issue, and we only need to wait until the client meeting to double check everything?

**Comment by Tian-Tan** [comment]
All of the dropdown tables have been fully implemented with
1. Multiple-column constraints (e897b352110775dd7ba2b93b4924f7211c4cdac8)
2. Standardized table formatting (d9137b3fffba8119268f976c4de005bdcc92a20c)
3. Sample data (Done in test server)

With the exception of the fields "Herbarium" (Which is not required to be reproduced in Symbiota), "ID Qualifier" (Is reproduced in the php file), "Prep method" and "Format" (Is controlled but dropdown might not be necessary/can be implemented in the php file).

**Comment by ttaliacc** [comment]
This issue is related to issue #34. Close this to avoid redundancy.
